# Cargo configuration optimized for local development

[build]
# Use all available CPU cores for parallel builds (default behavior)

[target.x86_64-apple-darwin]
linker = "clang"

[target.aarch64-apple-darwin]
linker = "clang"

[profile.dev]
# Optimized for fast local development cycles
incremental = true
debug = 1
opt-level = 0

[profile.test]
# Optimized test builds
debug = 1
opt-level = 1
incremental = true

[profile.release]
# Production releases
debug = false
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"

[profile.bench]
# Performance benchmarks
debug = false
opt-level = 3
lto = true
codegen-units = 1