# Mise configuration for host development
# Language runtimes available on host with proper pip configuration

[settings]
verbose = false
experimental = true

[tools]
# Python for AI/ML work and general scripting
python = "3.11"

# Node.js for tooling and web development
node = "lts"

[env]
# Development settings
EDITOR = "nvim"
PAGER = "bat"

# Rust environment variables
RUST_BACKTRACE = "1"

# Python environment - FIXED: Allow pip installs when needed
# Don't require virtualenv for mise-managed Python global tools
# Individual projects should still use virtual environments
PYTHONPATH = "."

# NOTE: Removed PIP_REQUIRE_VIRTUALENV=true to fix global pip installs
# Projects should use poetry/pipenv/venv for isolation